---
development:
  cloud_name: vmakoed
  api_key: '973619236396194'
  api_secret: 8KO3Cj8X8oU1yheVXUT97c5Ua1w
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: vmakoed
  api_key: '973619236396194'
  api_secret: 8KO3Cj8X8oU1yheVXUT97c5Ua1w
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: vmakoed
  api_key: '973619236396194'
  api_secret: 8KO3Cj8X8oU1yheVXUT97c5Ua1w
  enhance_image_tag: true
  static_image_support: false
