development:
  adapter: postgresql
  encoding: utf8
  database: sitemaker_database
  pool: 5
  timeout: 5000
  username: eugene
  password:


test:
  adapter: postgresql
  encoding: utf8
  database: sitemaker_database
  pool: 5
  timeout: 5000
  username: eugene
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: sitemaker_database
  pool: 5
  timeout: 5000

