development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sitemaker_database
  pool: 5
  username: root
  password: lenovo_a820
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sitemaker_database
  pool: 5
  username: root
  password: lenovo_a820
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: homework_production
  username: homework
  password: <%= ENV['HOMEWORK_DATABASE_PASSWORD'] %>
